### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by rtallarr**
github tokens must not start with github

### CODE REVIEW

**Comment by michal-h21** [comment]
Do you have any documentation for that? Is this some recent change? I think [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) should be OK.

**Comment by michal-h21** [comment]
@rtallarr Hi, I think you try to replace the example document with your resume. I guess this is a mistake?

**Comment by rtallarr** [comment]
sorry, I forgot I used master for that

**Comment by rtallarr** [comment]
The documentation can be found here [Docs](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions).
It states: 
> Names must not start with the `GITHUB_` prefix.

**Pull request closed without merging**
